// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/orders/orders.proto

package orders

// OrderType represents the type of order
type OrderType int32

// OrderSide represents the side of an order (buy/sell)
type OrderSide int32

// OrderStatus represents the status of an order
type OrderStatus int32

// TimeInForce represents the time in force for an order
type TimeInForce int32

// OrderType enum values
const (
	OrderType_MARKET     OrderType = 0
	OrderType_LIMIT      OrderType = 1
	OrderType_STOP       OrderType = 2
	OrderType_STOP_LIMIT OrderType = 3
	OrderType_TRAILING   OrderType = 4
	OrderType_IOC_ORDER  OrderType = 5
	OrderType_FOK_ORDER  OrderType = 6
	OrderType_CONDITIONAL OrderType = 7
)

// OrderSide enum values
const (
	OrderSide_BUY  OrderSide = 0
	OrderSide_SELL OrderSide = 1
)

// OrderStatus enum values
const (
	OrderStatus_NEW        OrderStatus = 0
	OrderStatus_PARTIAL    OrderStatus = 1
	OrderStatus_FILLED     OrderStatus = 2
	OrderStatus_CANCELLED  OrderStatus = 3
	OrderStatus_REJECTED   OrderStatus = 4
	OrderStatus_EXPIRED    OrderStatus = 5
	OrderStatus_PENDING    OrderStatus = 6
	OrderStatus_PROCESSING OrderStatus = 7
)

// TimeInForce enum values
const (
	TimeInForce_GTC TimeInForce = 0
	TimeInForce_IOC TimeInForce = 1
	TimeInForce_FOK TimeInForce = 2
	TimeInForce_DAY TimeInForce = 3
	TimeInForce_GTD TimeInForce = 4
)

