// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/marketdata/marketdata.proto

package marketdata

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketDataService_GetMarketData_FullMethodName     = "/marketdata.MarketDataService/GetMarketData"
	MarketDataService_StreamMarketData_FullMethodName  = "/marketdata.MarketDataService/StreamMarketData"
	MarketDataService_GetHistoricalData_FullMethodName = "/marketdata.MarketDataService/GetHistoricalData"
	MarketDataService_GetSymbols_FullMethodName        = "/marketdata.MarketDataService/GetSymbols"
)

// MarketDataServiceClient is the client API for MarketDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MarketDataService provides market data functionality
type MarketDataServiceClient interface {
	// GetMarketData gets market data for a symbol
	GetMarketData(ctx context.Context, in *MarketDataRequest, opts ...grpc.CallOption) (*MarketDataResponse, error)
	// StreamMarketData streams market data for a symbol
	StreamMarketData(ctx context.Context, in *MarketDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MarketDataResponse], error)
	// GetHistoricalData gets historical market data for a symbol
	GetHistoricalData(ctx context.Context, in *HistoricalDataRequest, opts ...grpc.CallOption) (*HistoricalDataResponse, error)
	// GetSymbols gets available symbols
	GetSymbols(ctx context.Context, in *SymbolsRequest, opts ...grpc.CallOption) (*SymbolsResponse, error)
}

type marketDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketDataServiceClient(cc grpc.ClientConnInterface) MarketDataServiceClient {
	return &marketDataServiceClient{cc}
}

func (c *marketDataServiceClient) GetMarketData(ctx context.Context, in *MarketDataRequest, opts ...grpc.CallOption) (*MarketDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarketDataResponse)
	err := c.cc.Invoke(ctx, MarketDataService_GetMarketData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketDataServiceClient) StreamMarketData(ctx context.Context, in *MarketDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MarketDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MarketDataService_ServiceDesc.Streams[0], MarketDataService_StreamMarketData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MarketDataRequest, MarketDataResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketDataService_StreamMarketDataClient = grpc.ServerStreamingClient[MarketDataResponse]

func (c *marketDataServiceClient) GetHistoricalData(ctx context.Context, in *HistoricalDataRequest, opts ...grpc.CallOption) (*HistoricalDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoricalDataResponse)
	err := c.cc.Invoke(ctx, MarketDataService_GetHistoricalData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketDataServiceClient) GetSymbols(ctx context.Context, in *SymbolsRequest, opts ...grpc.CallOption) (*SymbolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SymbolsResponse)
	err := c.cc.Invoke(ctx, MarketDataService_GetSymbols_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketDataServiceServer is the server API for MarketDataService service.
// All implementations must embed UnimplementedMarketDataServiceServer
// for forward compatibility.
//
// MarketDataService provides market data functionality
type MarketDataServiceServer interface {
	// GetMarketData gets market data for a symbol
	GetMarketData(context.Context, *MarketDataRequest) (*MarketDataResponse, error)
	// StreamMarketData streams market data for a symbol
	StreamMarketData(*MarketDataRequest, grpc.ServerStreamingServer[MarketDataResponse]) error
	// GetHistoricalData gets historical market data for a symbol
	GetHistoricalData(context.Context, *HistoricalDataRequest) (*HistoricalDataResponse, error)
	// GetSymbols gets available symbols
	GetSymbols(context.Context, *SymbolsRequest) (*SymbolsResponse, error)
	mustEmbedUnimplementedMarketDataServiceServer()
}

// UnimplementedMarketDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketDataServiceServer struct{}

func (UnimplementedMarketDataServiceServer) GetMarketData(context.Context, *MarketDataRequest) (*MarketDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMarketData not implemented")
}
func (UnimplementedMarketDataServiceServer) StreamMarketData(*MarketDataRequest, grpc.ServerStreamingServer[MarketDataResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamMarketData not implemented")
}
func (UnimplementedMarketDataServiceServer) GetHistoricalData(context.Context, *HistoricalDataRequest) (*HistoricalDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistoricalData not implemented")
}
func (UnimplementedMarketDataServiceServer) GetSymbols(context.Context, *SymbolsRequest) (*SymbolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSymbols not implemented")
}
func (UnimplementedMarketDataServiceServer) mustEmbedUnimplementedMarketDataServiceServer() {}
func (UnimplementedMarketDataServiceServer) testEmbeddedByValue()                           {}

// UnsafeMarketDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketDataServiceServer will
// result in compilation errors.
type UnsafeMarketDataServiceServer interface {
	mustEmbedUnimplementedMarketDataServiceServer()
}

func RegisterMarketDataServiceServer(s grpc.ServiceRegistrar, srv MarketDataServiceServer) {
	// If the following call pancis, it indicates UnimplementedMarketDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketDataService_ServiceDesc, srv)
}

func _MarketDataService_GetMarketData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).GetMarketData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketDataService_GetMarketData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).GetMarketData(ctx, req.(*MarketDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketDataService_StreamMarketData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MarketDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketDataServiceServer).StreamMarketData(m, &grpc.GenericServerStream[MarketDataRequest, MarketDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MarketDataService_StreamMarketDataServer = grpc.ServerStreamingServer[MarketDataResponse]

func _MarketDataService_GetHistoricalData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoricalDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).GetHistoricalData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketDataService_GetHistoricalData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).GetHistoricalData(ctx, req.(*HistoricalDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketDataService_GetSymbols_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SymbolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).GetSymbols(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketDataService_GetSymbols_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).GetSymbols(ctx, req.(*SymbolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketDataService_ServiceDesc is the grpc.ServiceDesc for MarketDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marketdata.MarketDataService",
	HandlerType: (*MarketDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMarketData",
			Handler:    _MarketDataService_GetMarketData_Handler,
		},
		{
			MethodName: "GetHistoricalData",
			Handler:    _MarketDataService_GetHistoricalData_Handler,
		},
		{
			MethodName: "GetSymbols",
			Handler:    _MarketDataService_GetSymbols_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMarketData",
			Handler:       _MarketDataService_StreamMarketData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/marketdata/marketdata.proto",
}
