linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - misspell
    - ineffassign
    - staticcheck

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/abdoElHodaky/tradSys

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
