linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - revive
    - gofmt
    - goimports
    - misspell
    - prealloc

linters-settings:
  govet:
    check-shadowing: true
  revive:
    rules:
      - name: var-naming
        severity: warning
        disabled: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0

