version: 2.1

executors:
  go-executor:
    docker:
      - image: cimg/go:1.20
    working_directory: ~/project

jobs:
  checkout_code:
    executor: go-executor
    steps:
      - checkout
      - run: git submodule update --init --recursive

  dependencies:
    executor: go-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Download Go modules
          command: go mod download
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - ~/go/pkg/mod

  lint:
    executor: go-executor
    steps:
      - checkout
      - run:
          name: Install golangci-lint
          command: |
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
      - run:
          name: Run golangci-lint
          command: golangci-lint run --timeout 5m

  test:
    executor: go-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Run Tests
          command: go test -v ./...
      - store_test_results:
          path: test-results

  build:
    executor: go-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Build
          command: go build -v ./...

workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - dependencies:
          requires:
            - checkout_code
      - lint:
          requires:
            - dependencies
      - test:
          requires:
            - dependencies
      - build:
          requires:
            - test
            - lint
