// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/orders/orders.proto

package orders

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderSide represents the side of an order
type OrderSide int32

const (
	OrderSide_BUY  OrderSide = 0
	OrderSide_SELL OrderSide = 1
)

// Enum value maps for OrderSide.
var (
	OrderSide_name = map[int32]string{
		0: "BUY",
		1: "SELL",
	}
	OrderSide_value = map[string]int32{
		"BUY":  0,
		"SELL": 1,
	}
)

func (x OrderSide) Enum() *OrderSide {
	p := new(OrderSide)
	*p = x
	return p
}

func (x OrderSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderSide) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_orders_orders_proto_enumTypes[0].Descriptor()
}

func (OrderSide) Type() protoreflect.EnumType {
	return &file_proto_orders_orders_proto_enumTypes[0]
}

func (x OrderSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderSide.Descriptor instead.
func (OrderSide) EnumDescriptor() ([]byte, []int) {
	return file_proto_orders_orders_proto_rawDescGZIP(), []int{0}
}

// OrderType represents the type of an order
type OrderType int32

const (
	OrderType_MARKET      OrderType = 0
	OrderType_LIMIT       OrderType = 1
	OrderType_STOP        OrderType = 2
	OrderType_STOP_LIMIT  OrderType = 3
	OrderType_TRAILING    OrderType = 4
	OrderType_IOC_ORDER   OrderType = 5
	OrderType_FOK_ORDER   OrderType = 6
	OrderType_CONDITIONAL OrderType = 7
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "MARKET",
		1: "LIMIT",
		2: "STOP",
		3: "STOP_LIMIT",
		4: "TRAILING",
		5: "IOC_ORDER",
		6: "FOK_ORDER",
		7: "CONDITIONAL",
	}
	OrderType_value = map[string]int32{
		"MARKET":      0,
		"LIMIT":       1,
		"STOP":        2,
		"STOP_LIMIT":  3,
		"TRAILING":    4,
		"IOC_ORDER":   5,
		"FOK_ORDER":   6,
		"CONDITIONAL": 7,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_orders_orders_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_proto_orders_orders_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_proto_orders_orders_proto_rawDescGZIP(), []int{1}
}

// OrderStatus represents the status of an order
type OrderStatus int32

const (
	OrderStatus_NEW        OrderStatus = 0
	OrderStatus_PARTIAL    OrderStatus = 1
	OrderStatus_FILLED     OrderStatus = 2
	OrderStatus_CANCELLED  OrderStatus = 3
	OrderStatus_REJECTED   OrderStatus = 4
	OrderStatus_EXPIRED    OrderStatus = 5
	OrderStatus_PENDING    OrderStatus = 6
	OrderStatus_PROCESSING OrderStatus = 7
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "NEW",
		1: "PARTIAL",
		2: "FILLED",
		3: "CANCELLED",
		4: "REJECTED",
		5: "EXPIRED",
		6: "PENDING",
		7: "PROCESSING",
	}
	OrderStatus_value = map[string]int32{
		"NEW":        0,
		"PARTIAL":    1,
		"FILLED":     2,
		"CANCELLED":  3,
		"REJECTED":   4,
		"EXPIRED":    5,
		"PENDING":    6,
		"PROCESSING": 7,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_orders_orders_proto_enumTypes[2].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_proto_orders_orders_proto_enumTypes[2]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_orders_orders_proto_rawDescGZIP(), []int{2}
}

// TimeInForce represents the time in force of an order
type TimeInForce int32

const (
	TimeInForce_GTC TimeInForce = 0
	TimeInForce_IOC TimeInForce = 1
	TimeInForce_FOK TimeInForce = 2
	TimeInForce_DAY TimeInForce = 3
	TimeInForce_GTD TimeInForce = 4
)

// Enum value maps for TimeInForce.
var (
	TimeInForce_name = map[int32]string{
		0: "GTC",
		1: "IOC",
		2: "FOK",
		3: "DAY",
		4: "GTD",
	}
	TimeInForce_value = map[string]int32{
		"GTC": 0,
		"IOC": 1,
		"FOK": 2,
		"DAY": 3,
		"GTD": 4,
	}
)

func (x TimeInForce) Enum() *TimeInForce {
	p := new(TimeInForce)
	*p = x
	return p
}

func (x TimeInForce) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeInForce) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_orders_orders_proto_enumTypes[3].Descriptor()
}

func (TimeInForce) Type() protoreflect.EnumType {
	return &file_proto_orders_orders_proto_enumTypes[3]
}

func (x TimeInForce) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeInForce.Descriptor instead.
func (TimeInForce) EnumDescriptor() ([]byte, []int) {
	return file_proto_orders_orders_proto_rawDescGZIP(), []int{3}
}

// CreateOrderRequest represents a request to create an order
type CreateOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID of the order
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Account ID of the order
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Symbol of the order
	Symbol string `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Side of the order
	Side OrderSide `protobuf:"varint,4,opt,name=side,proto3,enum=orders.OrderSide" json:"side,omitempty"`
	// Type of the order
	Type OrderType `protobuf:"varint,5,opt,name=type,proto3,enum=orders.OrderType" json:"type,omitempty"`
	// Quantity of the order
	Quantity float64 `protobuf:"fixed64,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Price of the order
	Price float64 `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	// Stop price of the order
	StopPrice float64 `protobuf:"fixed64,8,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`
	// Trailing offset of the order
	TrailingOffset float64 `protobuf:"fixed64,9,opt,name=trailing_offset,json=trailingOffset,proto3" json:"trailing_offset,omitempty"`
	// Time in force of the order
	TimeInForce TimeInForce `protobuf:"varint,10,opt,name=time_in_force,json=timeInForce,proto3,enum=orders.TimeInForce" json:"time_in_force,omitempty"`
	// Client order ID of the order
	ClientOrderId string `protobuf:"bytes,11,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	// Stop loss price of the order
	StopLoss float64 `protobuf:"fixed64,12,opt,name=stop_loss,json=stopLoss,proto3" json:"stop_loss,omitempty"`
	// Take profit price of the order
	TakeProfit float64 `protobuf:"fixed64,13,opt,name=take_profit,json=takeProfit,proto3" json:"take_profit,omitempty"`
	// Expiry time of the order
	ExpiresAt int64 `protobuf:"varint,14,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Notes for the order
	Notes         string `protobuf:"bytes,15,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_proto_orders_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_orders_orders_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CreateOrderRequest) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_BUY
}

func (x *CreateOrderRequest) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_MARKET
}

func (x *CreateOrderRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateOrderRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateOrderRequest) GetStopPrice() float64 {
	if x != nil {
		return x.StopPrice
	}
	return 0
}

func (x *CreateOrderRequest) GetTrailingOffset() float64 {
	if x != nil {
		return x.TrailingOffset
	}
	return 0
}

func (x *CreateOrderRequest) GetTimeInForce() TimeInForce {
	if x != nil {
		return x.TimeInForce
	}
	return TimeInForce_GTC
}

func (x *CreateOrderRequest) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *CreateOrderRequest) GetStopLoss() float64 {
	if x != nil {
		return x.StopLoss
	}
	return 0
}

func (x *CreateOrderRequest) GetTakeProfit() float64 {
	if x != nil {
		return x.TakeProfit
	}
	return 0
}

func (x *CreateOrderRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *CreateOrderRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

// GetOrderRequest represents a request to get an order
type GetOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the order
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// User ID of the order
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_proto_orders_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_orders_orders_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// CancelOrderRequest represents a request to cancel an order
type CancelOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the order
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// User ID of the order
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_proto_orders_orders_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_orders_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_orders_orders_proto_rawDescGZIP(), []int{2}
}

func (x *CancelOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancelOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetOrdersRequest represents a request to get orders
type GetOrdersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID of the orders
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Account ID of the orders
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Symbol of the orders
	Symbol string `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Side of the orders
	Side OrderSide `protobuf:"varint,4,opt,name=side,proto3,enum=orders.OrderSide" json:"side,omitempty"`
	// Status of the orders
	Status OrderStatus `protobuf:"varint,5,opt,name=status,proto3,enum=orders.OrderStatus" json:"status,omitempty"`
	// Start time for the orders
	StartTime int64 `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// End time for the orders
	EndTime int64 `protobuf:"varint,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Limit for the number of orders
	Limit int32 `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset for pagination
	Offset        int32 `protobuf:"varint,9,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersRequest) Reset() {
	*x = GetOrdersRequest{}
	mi := &file_proto_orders_orders_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersRequest) ProtoMessage() {}

func (x *GetOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_orders_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersRequest) Descriptor() ([]byte, []int) {
	return file_proto_orders_orders_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrdersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetOrdersRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetOrdersRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetOrdersRequest) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_BUY
}

func (x *GetOrdersRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_NEW
}

func (x *GetOrdersRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetOrdersRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *GetOrdersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetOrdersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// GetOrdersResponse represents a response with orders
type GetOrdersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Orders in the response
	Orders []*OrderResponse `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	// Total number of orders
	Total         int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersResponse) Reset() {
	*x = GetOrdersResponse{}
	mi := &file_proto_orders_orders_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersResponse) ProtoMessage() {}

func (x *GetOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_orders_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersResponse) Descriptor() ([]byte, []int) {
	return file_proto_orders_orders_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrdersResponse) GetOrders() []*OrderResponse {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *GetOrdersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// StreamOrdersRequest represents a request to stream orders
type StreamOrdersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// User ID of the orders
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Account ID of the orders
	AccountId string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Symbol of the orders
	Symbol        string `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOrdersRequest) Reset() {
	*x = StreamOrdersRequest{}
	mi := &file_proto_orders_orders_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOrdersRequest) ProtoMessage() {}

func (x *StreamOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_orders_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOrdersRequest.ProtoReflect.Descriptor instead.
func (*StreamOrdersRequest) Descriptor() ([]byte, []int) {
	return file_proto_orders_orders_proto_rawDescGZIP(), []int{5}
}

func (x *StreamOrdersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StreamOrdersRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *StreamOrdersRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

// OrderResponse represents an order response
type OrderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the order
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// User ID of the order
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Account ID of the order
	AccountId string `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Symbol of the order
	Symbol string `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// Side of the order
	Side OrderSide `protobuf:"varint,5,opt,name=side,proto3,enum=orders.OrderSide" json:"side,omitempty"`
	// Type of the order
	Type OrderType `protobuf:"varint,6,opt,name=type,proto3,enum=orders.OrderType" json:"type,omitempty"`
	// Quantity of the order
	Quantity float64 `protobuf:"fixed64,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Price of the order
	Price float64 `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	// Stop price of the order
	StopPrice float64 `protobuf:"fixed64,9,opt,name=stop_price,json=stopPrice,proto3" json:"stop_price,omitempty"`
	// Trailing offset of the order
	TrailingOffset float64 `protobuf:"fixed64,10,opt,name=trailing_offset,json=trailingOffset,proto3" json:"trailing_offset,omitempty"`
	// Time in force of the order
	TimeInForce TimeInForce `protobuf:"varint,11,opt,name=time_in_force,json=timeInForce,proto3,enum=orders.TimeInForce" json:"time_in_force,omitempty"`
	// Status of the order
	Status OrderStatus `protobuf:"varint,12,opt,name=status,proto3,enum=orders.OrderStatus" json:"status,omitempty"`
	// Filled quantity of the order
	FilledQty float64 `protobuf:"fixed64,13,opt,name=filled_qty,json=filledQty,proto3" json:"filled_qty,omitempty"`
	// Average price of the order
	AvgPrice float64 `protobuf:"fixed64,14,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	// Client order ID of the order
	ClientOrderId string `protobuf:"bytes,15,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	// Exchange order ID of the order
	ExchangeOrderId string `protobuf:"bytes,16,opt,name=exchange_order_id,json=exchangeOrderId,proto3" json:"exchange_order_id,omitempty"`
	// Stop loss price of the order
	StopLoss float64 `protobuf:"fixed64,17,opt,name=stop_loss,json=stopLoss,proto3" json:"stop_loss,omitempty"`
	// Take profit price of the order
	TakeProfit float64 `protobuf:"fixed64,18,opt,name=take_profit,json=takeProfit,proto3" json:"take_profit,omitempty"`
	// Notes for the order
	Notes string `protobuf:"bytes,19,opt,name=notes,proto3" json:"notes,omitempty"`
	// Created time of the order
	CreatedAt int64 `protobuf:"varint,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Updated time of the order
	UpdatedAt int64 `protobuf:"varint,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Expiry time of the order
	ExpiresAt     int64 `protobuf:"varint,22,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_proto_orders_orders_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_orders_orders_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_orders_orders_proto_rawDescGZIP(), []int{6}
}

func (x *OrderResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *OrderResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderResponse) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_BUY
}

func (x *OrderResponse) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_MARKET
}

func (x *OrderResponse) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderResponse) GetStopPrice() float64 {
	if x != nil {
		return x.StopPrice
	}
	return 0
}

func (x *OrderResponse) GetTrailingOffset() float64 {
	if x != nil {
		return x.TrailingOffset
	}
	return 0
}

func (x *OrderResponse) GetTimeInForce() TimeInForce {
	if x != nil {
		return x.TimeInForce
	}
	return TimeInForce_GTC
}

func (x *OrderResponse) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_NEW
}

func (x *OrderResponse) GetFilledQty() float64 {
	if x != nil {
		return x.FilledQty
	}
	return 0
}

func (x *OrderResponse) GetAvgPrice() float64 {
	if x != nil {
		return x.AvgPrice
	}
	return 0
}

func (x *OrderResponse) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *OrderResponse) GetExchangeOrderId() string {
	if x != nil {
		return x.ExchangeOrderId
	}
	return ""
}

func (x *OrderResponse) GetStopLoss() float64 {
	if x != nil {
		return x.StopLoss
	}
	return 0
}

func (x *OrderResponse) GetTakeProfit() float64 {
	if x != nil {
		return x.TakeProfit
	}
	return 0
}

func (x *OrderResponse) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *OrderResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *OrderResponse) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *OrderResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_proto_orders_orders_proto protoreflect.FileDescriptor

const file_proto_orders_orders_proto_rawDesc = "" +
	"\n" +
	"\x19proto/orders/orders.proto\x12\x06orders\"\x80\x04\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12%\n" +
	"\x04side\x18\x04 \x01(\x0e2\x11.orders.OrderSideR\x04side\x12%\n" +
	"\x04type\x18\x05 \x01(\x0e2\x11.orders.OrderTypeR\x04type\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x01R\bquantity\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"stop_price\x18\b \x01(\x01R\tstopPrice\x12'\n" +
	"\x0ftrailing_offset\x18\t \x01(\x01R\x0etrailingOffset\x127\n" +
	"\rtime_in_force\x18\n" +
	" \x01(\x0e2\x13.orders.TimeInForceR\vtimeInForce\x12&\n" +
	"\x0fclient_order_id\x18\v \x01(\tR\rclientOrderId\x12\x1b\n" +
	"\tstop_loss\x18\f \x01(\x01R\bstopLoss\x12\x1f\n" +
	"\vtake_profit\x18\r \x01(\x01R\n" +
	"takeProfit\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x0e \x01(\x03R\texpiresAt\x12\x14\n" +
	"\x05notes\x18\x0f \x01(\tR\x05notes\":\n" +
	"\x0fGetOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"=\n" +
	"\x12CancelOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x9e\x02\n" +
	"\x10GetOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12%\n" +
	"\x04side\x18\x04 \x01(\x0e2\x11.orders.OrderSideR\x04side\x12+\n" +
	"\x06status\x18\x05 \x01(\x0e2\x13.orders.OrderStatusR\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\x03R\aendTime\x12\x14\n" +
	"\x05limit\x18\b \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\t \x01(\x05R\x06offset\"X\n" +
	"\x11GetOrdersResponse\x12-\n" +
	"\x06orders\x18\x01 \x03(\v2\x15.orders.OrderResponseR\x06orders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"e\n" +
	"\x13StreamOrdersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\"\xde\x05\n" +
	"\rOrderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\x12%\n" +
	"\x04side\x18\x05 \x01(\x0e2\x11.orders.OrderSideR\x04side\x12%\n" +
	"\x04type\x18\x06 \x01(\x0e2\x11.orders.OrderTypeR\x04type\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x01R\bquantity\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12\x1d\n" +
	"\n" +
	"stop_price\x18\t \x01(\x01R\tstopPrice\x12'\n" +
	"\x0ftrailing_offset\x18\n" +
	" \x01(\x01R\x0etrailingOffset\x127\n" +
	"\rtime_in_force\x18\v \x01(\x0e2\x13.orders.TimeInForceR\vtimeInForce\x12+\n" +
	"\x06status\x18\f \x01(\x0e2\x13.orders.OrderStatusR\x06status\x12\x1d\n" +
	"\n" +
	"filled_qty\x18\r \x01(\x01R\tfilledQty\x12\x1b\n" +
	"\tavg_price\x18\x0e \x01(\x01R\bavgPrice\x12&\n" +
	"\x0fclient_order_id\x18\x0f \x01(\tR\rclientOrderId\x12*\n" +
	"\x11exchange_order_id\x18\x10 \x01(\tR\x0fexchangeOrderId\x12\x1b\n" +
	"\tstop_loss\x18\x11 \x01(\x01R\bstopLoss\x12\x1f\n" +
	"\vtake_profit\x18\x12 \x01(\x01R\n" +
	"takeProfit\x12\x14\n" +
	"\x05notes\x18\x13 \x01(\tR\x05notes\x12\x1d\n" +
	"\n" +
	"created_at\x18\x14 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x15 \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x16 \x01(\x03R\texpiresAt*\x1e\n" +
	"\tOrderSide\x12\a\n" +
	"\x03BUY\x10\x00\x12\b\n" +
	"\x04SELL\x10\x01*y\n" +
	"\tOrderType\x12\n" +
	"\n" +
	"\x06MARKET\x10\x00\x12\t\n" +
	"\x05LIMIT\x10\x01\x12\b\n" +
	"\x04STOP\x10\x02\x12\x0e\n" +
	"\n" +
	"STOP_LIMIT\x10\x03\x12\f\n" +
	"\bTRAILING\x10\x04\x12\r\n" +
	"\tIOC_ORDER\x10\x05\x12\r\n" +
	"\tFOK_ORDER\x10\x06\x12\x0f\n" +
	"\vCONDITIONAL\x10\a*v\n" +
	"\vOrderStatus\x12\a\n" +
	"\x03NEW\x10\x00\x12\v\n" +
	"\aPARTIAL\x10\x01\x12\n" +
	"\n" +
	"\x06FILLED\x10\x02\x12\r\n" +
	"\tCANCELLED\x10\x03\x12\f\n" +
	"\bREJECTED\x10\x04\x12\v\n" +
	"\aEXPIRED\x10\x05\x12\v\n" +
	"\aPENDING\x10\x06\x12\x0e\n" +
	"\n" +
	"PROCESSING\x10\a*:\n" +
	"\vTimeInForce\x12\a\n" +
	"\x03GTC\x10\x00\x12\a\n" +
	"\x03IOC\x10\x01\x12\a\n" +
	"\x03FOK\x10\x02\x12\a\n" +
	"\x03DAY\x10\x03\x12\a\n" +
	"\x03GTD\x10\x042\xd6\x02\n" +
	"\fOrderService\x12@\n" +
	"\vCreateOrder\x12\x1a.orders.CreateOrderRequest\x1a\x15.orders.OrderResponse\x12:\n" +
	"\bGetOrder\x12\x17.orders.GetOrderRequest\x1a\x15.orders.OrderResponse\x12@\n" +
	"\vCancelOrder\x12\x1a.orders.CancelOrderRequest\x1a\x15.orders.OrderResponse\x12@\n" +
	"\tGetOrders\x12\x18.orders.GetOrdersRequest\x1a\x19.orders.GetOrdersResponse\x12D\n" +
	"\fStreamOrders\x12\x1b.orders.StreamOrdersRequest\x1a\x15.orders.OrderResponse0\x01B.Z,github.com/abdoElHodaky/tradSys/proto/ordersb\x06proto3"

var (
	file_proto_orders_orders_proto_rawDescOnce sync.Once
	file_proto_orders_orders_proto_rawDescData []byte
)

func file_proto_orders_orders_proto_rawDescGZIP() []byte {
	file_proto_orders_orders_proto_rawDescOnce.Do(func() {
		file_proto_orders_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_orders_orders_proto_rawDesc), len(file_proto_orders_orders_proto_rawDesc)))
	})
	return file_proto_orders_orders_proto_rawDescData
}

var file_proto_orders_orders_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_orders_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_orders_orders_proto_goTypes = []any{
	(OrderSide)(0),              // 0: orders.OrderSide
	(OrderType)(0),              // 1: orders.OrderType
	(OrderStatus)(0),            // 2: orders.OrderStatus
	(TimeInForce)(0),            // 3: orders.TimeInForce
	(*CreateOrderRequest)(nil),  // 4: orders.CreateOrderRequest
	(*GetOrderRequest)(nil),     // 5: orders.GetOrderRequest
	(*CancelOrderRequest)(nil),  // 6: orders.CancelOrderRequest
	(*GetOrdersRequest)(nil),    // 7: orders.GetOrdersRequest
	(*GetOrdersResponse)(nil),   // 8: orders.GetOrdersResponse
	(*StreamOrdersRequest)(nil), // 9: orders.StreamOrdersRequest
	(*OrderResponse)(nil),       // 10: orders.OrderResponse
}
var file_proto_orders_orders_proto_depIdxs = []int32{
	0,  // 0: orders.CreateOrderRequest.side:type_name -> orders.OrderSide
	1,  // 1: orders.CreateOrderRequest.type:type_name -> orders.OrderType
	3,  // 2: orders.CreateOrderRequest.time_in_force:type_name -> orders.TimeInForce
	0,  // 3: orders.GetOrdersRequest.side:type_name -> orders.OrderSide
	2,  // 4: orders.GetOrdersRequest.status:type_name -> orders.OrderStatus
	10, // 5: orders.GetOrdersResponse.orders:type_name -> orders.OrderResponse
	0,  // 6: orders.OrderResponse.side:type_name -> orders.OrderSide
	1,  // 7: orders.OrderResponse.type:type_name -> orders.OrderType
	3,  // 8: orders.OrderResponse.time_in_force:type_name -> orders.TimeInForce
	2,  // 9: orders.OrderResponse.status:type_name -> orders.OrderStatus
	4,  // 10: orders.OrderService.CreateOrder:input_type -> orders.CreateOrderRequest
	5,  // 11: orders.OrderService.GetOrder:input_type -> orders.GetOrderRequest
	6,  // 12: orders.OrderService.CancelOrder:input_type -> orders.CancelOrderRequest
	7,  // 13: orders.OrderService.GetOrders:input_type -> orders.GetOrdersRequest
	9,  // 14: orders.OrderService.StreamOrders:input_type -> orders.StreamOrdersRequest
	10, // 15: orders.OrderService.CreateOrder:output_type -> orders.OrderResponse
	10, // 16: orders.OrderService.GetOrder:output_type -> orders.OrderResponse
	10, // 17: orders.OrderService.CancelOrder:output_type -> orders.OrderResponse
	8,  // 18: orders.OrderService.GetOrders:output_type -> orders.GetOrdersResponse
	10, // 19: orders.OrderService.StreamOrders:output_type -> orders.OrderResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_orders_orders_proto_init() }
func file_proto_orders_orders_proto_init() {
	if File_proto_orders_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_orders_orders_proto_rawDesc), len(file_proto_orders_orders_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_orders_orders_proto_goTypes,
		DependencyIndexes: file_proto_orders_orders_proto_depIdxs,
		EnumInfos:         file_proto_orders_orders_proto_enumTypes,
		MessageInfos:      file_proto_orders_orders_proto_msgTypes,
	}.Build()
	File_proto_orders_orders_proto = out.File
	file_proto_orders_orders_proto_goTypes = nil
	file_proto_orders_orders_proto_depIdxs = nil
}
