apiVersion: v1
kind: ConfigMap
metadata:
  name: tradingsys-config
  namespace: tradingsys
data:
  config.yaml: |
    server:
      host: "0.0.0.0"
      port: 8080
      read_timeout: "30s"
      write_timeout: "30s"
      idle_timeout: "120s"
      shutdown_timeout: "30s"
    
    database:
      host: "postgres-service"
      port: 5432
      name: "tradingsys"
      user: "tradingsys"
      ssl_mode: "require"
      max_open_conns: 25
      max_idle_conns: 5
      conn_max_lifetime: "5m"
    
    redis:
      host: "redis-service"
      port: 6379
      db: 0
      pool_size: 10
      min_idle_conns: 5
      dial_timeout: "5s"
      read_timeout: "3s"
      write_timeout: "3s"
      pool_timeout: "4s"
      idle_timeout: "5m"
    
    matching:
      engine_type: "unified"
      max_orders_per_symbol: 10000
      worker_count: 4
      batch_size: 100
      flush_interval: "100ms"
    
    logging:
      level: "info"
      format: "json"
      output: "stdout"
    
    metrics:
      enabled: true
      port: 9090
      path: "/metrics"
    
    tracing:
      enabled: true
      service_name: "tradingsys"
      jaeger_endpoint: "http://jaeger-collector:14268/api/traces"
    
    performance:
      enable_profiling: true
      profiling_port: 6060
      circuit_breaker:
        max_requests: 100
        interval: "10s"
        timeout: "60s"
        max_consecutive_failures: 5
      
      rate_limiter:
        requests_per_second: 1000
        burst: 2000
      
      object_pool:
        max_size: 1000
        cleanup_interval: "5m"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tradingsys-config
  namespace: tradingsys-staging
data:
  config.yaml: |
    server:
      host: "0.0.0.0"
      port: 8080
      read_timeout: "30s"
      write_timeout: "30s"
      idle_timeout: "120s"
      shutdown_timeout: "30s"
    
    database:
      host: "postgres-service"
      port: 5432
      name: "tradingsys_staging"
      user: "tradingsys"
      ssl_mode: "require"
      max_open_conns: 10
      max_idle_conns: 2
      conn_max_lifetime: "5m"
    
    redis:
      host: "redis-service"
      port: 6379
      db: 1
      pool_size: 5
      min_idle_conns: 2
      dial_timeout: "5s"
      read_timeout: "3s"
      write_timeout: "3s"
      pool_timeout: "4s"
      idle_timeout: "5m"
    
    matching:
      engine_type: "unified"
      max_orders_per_symbol: 1000
      worker_count: 2
      batch_size: 50
      flush_interval: "200ms"
    
    logging:
      level: "debug"
      format: "json"
      output: "stdout"
    
    metrics:
      enabled: true
      port: 9090
      path: "/metrics"
    
    tracing:
      enabled: true
      service_name: "tradingsys-staging"
      jaeger_endpoint: "http://jaeger-collector:14268/api/traces"
    
    performance:
      enable_profiling: true
      profiling_port: 6060
      circuit_breaker:
        max_requests: 50
        interval: "10s"
        timeout: "60s"
        max_consecutive_failures: 3
      
      rate_limiter:
        requests_per_second: 100
        burst: 200
      
      object_pool:
        max_size: 100
        cleanup_interval: "5m"
