server:
  host: "0.0.0.0"
  port: 8080

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: ""
  name: "tradsys"
  sslmode: "disable"

websocket:
  host: "0.0.0.0"
  port: 8081
  path: "/ws"
  max_connections: 1000

peerjs:
  host: "0.0.0.0"
  port: 9000
  path: "/peerjs"

market_data:
  sources:
    - "internal"
  symbols:
    - "BTC/USD"
    - "ETH/USD"

risk:
  max_order_value: 10000.0
  max_position_value: 50000.0
  max_drawdown: 0.1
  max_leverage: 5.0
  stop_loss_percent: 0.05
  take_profit_percent: 0.1

monitoring:
  prometheus_port: 9090
  log_level: "info"

auth:
  jwt_secret: "change_this_in_production"
  token_duration: 60  # minutes
