# TradSys Unified Configuration
# This configuration file consolidates all TradSys components

# Server Configuration
server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s
  tls:
    enabled: false
    cert_file: ""
    key_file: ""

# Core Trading Engine Configuration
core:
  order_matching:
    algorithm: "fifo"  # fifo, pro_rata, time_price_priority
    timeout: 100µs
  risk_engine:
    max_position_size: 1000000.0
    max_order_value: 100000.0
    check_timeout: 10µs
  settlement:
    batch_size: 100
    timeout: 1ms

# Exchange Connectivity Configuration
connectivity:
  timeout: 5s
  retries: 3
  exchanges:
    - name: "binance"
      endpoint: "https://api.binance.com"
      api_key: "${BINANCE_API_KEY}"
      secret: "${BINANCE_SECRET}"
      enabled: true
    - name: "coinbase"
      endpoint: "https://api.coinbase.com"
      api_key: "${COINBASE_API_KEY}"
      secret: "${COINBASE_SECRET}"
      enabled: false

# Compliance Engine Configuration
compliance:
  audit_log:
    enabled: true
    path: "/var/log/tradsys/audit.log"
  reporting:
    enabled: true
    frequency: 1h
    output: "/var/log/tradsys/reports/"
  rules:
    - name: "position_limit"
      type: "position_check"
      enabled: true
      parameters:
        max_position: 1000000
    - name: "order_value_limit"
      type: "order_check"
      enabled: true
      parameters:
        max_value: 100000

# Algorithmic Strategies Configuration
strategies:
  enabled:
    - "mean_reversion"
    - "momentum"
    - "market_making"
  parameters:
    mean_reversion:
      lookback_period: 20
      threshold: 2.0
    momentum:
      fast_period: 12
      slow_period: 26
    market_making:
      spread: 0.001
      max_inventory: 10000

# Database Configuration
database:
  driver: "postgres"
  host: "${TRADSYS_DB_HOST:-localhost}"
  port: 5432
  database: "tradsys"
  username: "${TRADSYS_DB_USER:-tradsys}"
  password: "${TRADSYS_DB_PASSWORD}"
  ssl_mode: "disable"
  max_connections: 10

# Redis Configuration
redis:
  host: "${TRADSYS_REDIS_HOST:-localhost}"
  port: 6379
  password: "${TRADSYS_REDIS_PASSWORD}"
  database: 0

# Logging Configuration
logging:
  level: "info"  # debug, info, warn, error, fatal
  format: "json"  # json, text
  output: "stdout"  # stdout, stderr, file path

# Metrics Configuration
metrics:
  enabled: true
  port: 9090
  path: "/metrics"
  namespace: "tradsys"

# Security Configuration
security:
  jwt:
    secret: "${TRADSYS_JWT_SECRET}"
    expiration: 24h
  rate_limit:
    enabled: true
    rps: 1000

# Performance Tuning
performance:
  # Order processing targets
  order_processing_timeout: 100µs
  risk_check_timeout: 10µs
  matching_timeout: 50µs
  settlement_timeout: 1ms
  
  # Memory settings
  gc_target_percentage: 100
  max_memory_mb: 2048
  
  # Connection pools
  db_max_idle_conns: 5
  db_max_open_conns: 10
  redis_pool_size: 10

# Environment-specific overrides
# These can be overridden by environment variables:
# TRADSYS_PORT, TRADSYS_HOST, TRADSYS_LOG_LEVEL, etc.
