# TradSys HFT Trading System Configuration

# Core Trading Engine Configuration
trading:
  # Order matching engine settings
  order_matching:
    max_orders_per_symbol: 100000
    price_precision: 8
    quantity_precision: 8
    matching_algorithm: "price_time_priority"
    enable_iceberg_orders: true
    enable_stop_orders: true
    max_order_size: 1000000.0
    min_order_size: 0.00000001
    
  # Execution engine settings
  execution:
    max_execution_time: "100µs"
    enable_partial_fills: true
    fee_rate: 0.0001  # 0.01%
    commission_rate: 0.0005  # 0.05%
    max_slippage: 0.001  # 0.1%
    execution_timeout: "100µs"
    
  # Settlement processor settings
  settlement:
    settlement_cycle: "T+0"  # Real-time settlement
    workers: 4
    batch_size: 100
    processing_timeout: "1s"
    max_retries: 3
    retry_delay: "100ms"
    
  # Position manager settings
  positions:
    enable_real_time_pnl: true
    pnl_calculation_interval: "1s"
    position_limits_check: true
    enable_margin_trading: true
    margin_requirement: 0.1  # 10%
    
  # Price level manager settings
  price_levels:
    max_levels_per_side: 1000
    level_aggregation: true
    spread_calculation_interval: "100ms"
    market_depth_levels: 20

# Performance Configuration
performance:
  # Latency targets (microseconds)
  targets:
    order_processing: 100
    websocket_latency: 50
    database_query: 1000
    settlement_processing: 1000
    risk_check: 10
    
  # Throughput targets
  throughput:
    orders_per_second: 100000
    trades_per_second: 50000
    market_data_updates_per_second: 1000000
    
  # Memory management
  memory:
    gc_percent: 200
    memory_limit: "2GB"
    enable_object_pooling: true
    pool_sizes:
      order_pool: 10000
      message_pool: 50000
      response_pool: 20000
      
  # Database optimization
  database:
    sqlite_wal: true
    sqlite_cache_size: 10000
    sqlite_mmap_size: "256MB"
    prepared_statements: true
    connection_pool_size: 10
    max_idle_connections: 5
    connection_max_lifetime: "1h"

# Monitoring and Metrics
monitoring:
  # Metrics collection
  metrics:
    enable_prometheus: true
    prometheus_port: 9090
    collection_interval: "1s"
    histogram_buckets: [10, 25, 50, 100, 250, 500, 1000, 2500, 5000]
    
  # Health checks
  health:
    enable_health_checks: true
    health_check_port: 8080
    health_check_interval: "30s"
    
  # Logging
  logging:
    level: "info"
    format: "json"
    enable_structured_logging: true
    log_file: "/var/log/tradsys/trading.log"
    max_file_size: "100MB"
    max_backups: 10
    max_age: 30  # days
    
# WebSocket Configuration
websocket:
  # Connection settings
  connection:
    max_connections: 10000
    read_buffer_size: 4096
    write_buffer_size: 4096
    handshake_timeout: "10s"
    
  # Message handling
  messaging:
    enable_compression: true
    compression_level: 1
    enable_binary_protocol: true
    message_queue_size: 10000
    broadcast_workers: 8
    
  # Rate limiting
  rate_limiting:
    messages_per_second: 1000
    burst_size: 100
    enable_per_connection_limits: true

# API Configuration
api:
  # HTTP server settings
  http:
    port: 8080
    read_timeout: "30s"
    write_timeout: "30s"
    idle_timeout: "120s"
    max_header_bytes: 1048576  # 1MB
    
  # Rate limiting
  rate_limiting:
    requests_per_second: 1000
    burst_size: 100
    enable_per_ip_limits: true
    
  # CORS settings
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    max_age: 86400  # 24 hours
    
# Security Configuration
security:
  # Authentication
  auth:
    jwt_secret: "${JWT_SECRET}"
    jwt_expiry: "24h"
    enable_refresh_tokens: true
    refresh_token_expiry: "7d"
    
  # TLS settings
  tls:
    enable_tls: false
    cert_file: "/etc/ssl/certs/tradsys.crt"
    key_file: "/etc/ssl/private/tradsys.key"
    min_version: "1.2"
    
  # Rate limiting
  rate_limiting:
    enable_global_rate_limiting: true
    global_requests_per_second: 10000
    enable_ddos_protection: true

