apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketdata
  labels:
    app: marketdata
spec:
  replicas: 3
  selector:
    matchLabels:
      app: marketdata
  template:
    metadata:
      labels:
        app: marketdata
    spec:
      containers:
      - name: marketdata
        image: tradsys/marketdata:latest
        ports:
        - containerPort: 8080
        env:
        - name: SERVICE_NAME
          value: "marketdata"
        - name: SERVICE_ADDRESS
          value: ":8080"
        - name: REGISTRY_TYPE
          value: "kubernetes"
        - name: BROKER_TYPE
          value: "nats"
        - name: BROKER_ADDRESSES
          value: "nats:4222"
        - name: TRACING_ENABLED
          value: "true"
        - name: TRACING_TYPE
          value: "jaeger"
        - name: TRACING_ADDRESS
          value: "jaeger-agent:6831"
        - name: METRICS_ENABLED
          value: "true"
        - name: RESILIENCE_CIRCUIT_BREAKER_ENABLED
          value: "true"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: marketdata
spec:
  selector:
    app: marketdata
  ports:
  - port: 8080
    targetPort: 8080

