apiVersion: v1
kind: Namespace
metadata:
  name: tradsys-prod
  labels:
    name: tradsys-prod
    environment: production
    app.kubernetes.io/name: tradsys
    app.kubernetes.io/instance: production
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: tradsys
    app.kubernetes.io/managed-by: kubernetes
  annotations:
    description: "TradSys production environment namespace"
    contact: "team@tradsys.com"
    cost-center: "trading-systems"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: tradsys-prod-quota
  namespace: tradsys-prod
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "20"
    configmaps: "20"
    pods: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: tradsys-prod-limits
  namespace: tradsys-prod
spec:
  limits:
  - default:
      cpu: "2"
      memory: "4Gi"
    defaultRequest:
      cpu: "500m"
      memory: "1Gi"
    type: Container
  - max:
      cpu: "8"
      memory: "16Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
    type: Container
