package models

import (
	"time"

	"gorm.io/gorm"
)

// Strategy represents a trading strategy
type Strategy struct {
	gorm.Model
	Name        string `gorm:"uniqueIndex;not null"`
	Description string
	Active      bool   `gorm:"not null;default:false"`
	Parameters  string `gorm:"type:text"` // JSON string of parameters
	Code        string `gorm:"type:text"` // Strategy code or reference
}

// StrategyExecution represents an execution of a strategy
type StrategyExecution struct {
	gorm.Model
	StrategyID   uint      `gorm:"index;not null"`
	Symbol       string    `gorm:"index;not null"`
	StartTime    time.Time `gorm:"not null"`
	EndTime      time.Time
	Status       string    `gorm:"not null"` // RUNNING, COMPLETED, FAILED, STOPPED
	ErrorMessage string
	Results      string    `gorm:"type:text"` // JSON string of results
}

// Signal represents a trading signal generated by a strategy
type Signal struct {
	gorm.Model
	StrategyID   uint      `gorm:"index;not null"`
	Symbol       string    `gorm:"index;not null"`
	Direction    string    `gorm:"not null"` // BUY, SELL, NEUTRAL
	Strength     float64   `gorm:"not null"` // 0.0 to 1.0
	GeneratedAt  time.Time `gorm:"index;not null"`
	ExpiresAt    time.Time
	Executed     bool      `gorm:"not null;default:false"`
	ExecutedAt   time.Time
	OrderID      string    `gorm:"index"`
	Notes        string
}

