name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Run go vet
        run: go vet ./cmd/tradsys/...

      - name: Run gofmt check
        run: |
          if [ "$(gofmt -l ./cmd/tradsys)" ]; then
            echo "The following files are not properly formatted:"
            gofmt -l ./cmd/tradsys
            exit 1
          fi

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install Protocol Buffers compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.31.0
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Generate Protocol Buffers code
        run: ./scripts/generate_proto.sh

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./cmd/tradsys/... ./internal/unified-config/...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
          fail_ci_if_error: false

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install Protocol Buffers compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.31.0
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Generate Protocol Buffers code
        run: ./scripts/generate_proto.sh

      - name: Build Main Application
        run: go build -v -o bin/tradsys ./cmd/tradsys

      # TODO: Fix configuration structure mismatch in micro services
      # The following services are temporarily disabled due to config structure issues:
      # - Gateway, Market Data, Orders, Risk, WebSocket services
      # These services expect Service, Registry, Tracing, Resilience config fields
      # that are not present in the unified config structure

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: bin/
